### PR TITLE
Fix import from wrong JAR.

### PR DESCRIPTION
**Pull request by mtbc**
IDE autocomplete picked the wrong class to import and I missed it.

### CODE REVIEW

**Comment by joshmoore** [comment]
Today's build is green. Good to merge. @mtbc: did the wrong import make it into a release version and if so, do we need to bump?

**Comment by mtbc** [comment]
Ta. This import was in OMERO 5.5.0.

I don't see that we need to bump but that might just be because I'm not understanding something.

**Comment by joshmoore** [comment]
> I don't see that we need to bump but that might just be because I'm not understanding something.

If there's a loss of function, i.e. it's _dangerous_ to use the wrong import, then we should release.

**Comment by mtbc** [comment]
Aha, understood. I believe all is fine on that front. :relieved:

**Comment by joshmoore** [comment]
Ok. Then merging and it can be rolled into the next release.

**Pull request merged**
