### PR TITLE
#170 Invocation of toString on an array

### LINKED ISSUE #170: Invocation of toString on an array.
https://github.com/ome/omero-server/blob/d64ded205c6a0d3b9b54327941fdf0fa8ef91c96/src/main/java/ome/services/search/AnnotatedWith.java#L214

Line 214

                notNullOrLikeOrEqual(qb, ann + ".ns", type[j], annotation[j]
                        .getNs(), useLike, values.caseSensitive);

Should variable **ann** be **ann[j]**? 

                notNullOrLikeOrEqual(qb, ann[j] + ".ns", type[j], annotation[j]
                        .getNs(), useLike, values.caseSensitive);

All other references in the method to **ann** are **ann[j]**.

### PR DESCRIPTION
**Pull request by scuniff**
fix #170

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by sbesson** [comment]
The code changes look reasonable and were included in the nightly CI builds with no regression in the unit and integration tests.

From a quick scan of the codebase, the only place where `AnnotatedWith` is created sets `useNamespace` to `False` so this block might never get executed https://github.com/ome/omero-server/blob/d64ded205c6a0d3b9b54327941fdf0fa8ef91c96/src/main/java/ome/services/SearchBean.java#L153
Is there a testing scenario that would be broken with the existing code and fixed by this change?

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Review by joshmoore — APPROVED** [review]
Thanks, @scuniff. As @sbesson mentions, this is likely code that is never run (making it equally difficult to test)

**Review by sbesson — APPROVED** [review]

**Pull request merged**
