### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by joshmoore** [comment]
@jburel : did the move of fulltext.Main need rolling back as well?

**Comment by jburel** [comment]
If we plan to only support one version of Ice,  the 3.6 folder does not make sense at all. 
If we keep the 3.6 folder, then fulltext.Main should be in since it is 3.6 specific. We will need adjustment for 3.7

**Comment by joshmoore** [comment]
Understood. But if you rolled back other 3.7 changes for the moment, should this one go to? How did you handle other similar files?

**Comment by jburel** [comment]
Similar files are under the 3.6 folder

**Comment by joshmoore** [comment]
But are moved in this set of changes? I'm trying to reduce git history churn if unnecessary (i.e. if we move to a single folder)

**Comment by joshmoore** [comment]
(Note: commit force-pushed away after chatting)

**Comment by joshmoore** [comment]
Thanks, guys.

**Pull request merged**
