### PR TITLE
Test

### PR DESCRIPTION
**Pull request by jburel**
Compile and run the tests
The tests should now be run via travis
To test locally, run:
``gradle test``

### CODE REVIEW

**Comment by pwalczysko** [comment]
```
gradle test

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 47s
6 actionable tasks: 5 executed, 1 up-to-date
```

**Comment by joshmoore** [comment]
The integration tests aren't yet being run anywhere, are they?

**Comment by jburel** [comment]
No. I was focusing this round on units test

**Comment by joshmoore** [comment]
The issue you had with accessing import from server tests also raises the issue if all the integration tests should be migrated back to OmeroJava

**Comment by jburel** [comment]
Ok to merge?

**Comment by jburel** [comment]
Actually I don't think any of those tests have been run for a long time.

**Comment by jburel** [comment]
integration tests is another epic by itself. Merging this PR for m6

**Pull request merged**
