### PR TITLE
Update changelog for v5.5.6 release.

### PR DESCRIPTION
**Pull request by mtbc**
Add a changelog entry for v5.5.6.

### CODE REVIEW

**Comment by jburel** [comment]
Will you also bump ``omero-common-test`` version?

**Comment by mtbc** [comment]
Heh, I didn't even know there was that dependency, yes I guess we should bump it to 5.5.5, thank you.

**Comment by jburel** [comment]
Thanks looks good

**Comment by jburel** [comment]
Thanks

**Pull request merged**
