### PR TITLE
M4

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by joshmoore** [comment]
@rgozim : do you intend travis to be green here?

**Comment by jburel** [comment]
Since ``m3`` has been replaced by ``SNAPSHOT``, in the current state this will never be green in travis.

**Comment by jburel** [comment]
@rgozim you will have to roll back the change to SNAPSHOT since it has already been done in
another PR

**Comment by joshmoore** [comment]
Green with artifactory jars. Merging and continuing.

**Pull request merged**
