### PR TITLE
Add Bio-Formats version metadata to configuration

### PR DESCRIPTION
**Pull request by chris-allan**
Useful to have server Bio-Formats version information available during development in configuration for query and comparison. Three new configuration options have been added:

 * `omero.bioformats.version` (Reflects the contents stored in Bio-Formats variable `loci.formats.FormatTools.VERSION`)
 * `omero.bioformats.vcs_revision` (Reflects the contents stored in Bio-Formats variable `loci.formats.FormatTools.VCS_REVISION`)
 * `omero.bioformats.date` (Reflects the contents stored in Bio-Formats variable `loci.formats.FormatTools.DATE`)

### CODE REVIEW

**Comment by joshmoore** [comment]
You're only accessing these via admin account? Or should they be made readable? https://github.com/ome/omero-common/blob/master/src/main/resources/ome/config.xml#L61

**Comment by chris-allan** [comment]
Was going to ask where those visibility assertions went. I'll make sure to add a companion PR.

**Comment by chris-allan** [comment]
@joshmoore: Companion PR opened...

 * ome/omero-common#33

**Comment by joshmoore** [comment]
Tested with root & public:

```
In [1]: c = client.sf.getConfigService()

In [2]: c.getConfigValue("omero.bioformats.version")
Out[2]: '6.7.0-SNAPSHOT'

In [3]: c.getConfigValue("omero.bioformats.vcs_version")
Out[3]: ''

In [4]: c.getConfigValue("omero.bioformats.date")
Out[4]: '26 April 2021'
```

I'm not sure if `vcs_version` is expected to be empty in this set up or not. Also, I could see dropping the `omero.` prefix if there are any objections, but otherwise, :+1:

**Comment by chris-allan** [comment]
Might be missing depending on how the JAR is built. Can you check the manifest and see if the empty string is in line with the implementation?

 * https://github.com/ome/bioformats/blob/develop/components/formats-api/src/loci/formats/FormatTools.java#L298

**Comment by chris-allan** [comment]
Ah, it's `vcs_revision` not `vcs_version`, @joshmoore.

**Comment by joshmoore** [comment]
Bingo.

```
In [2]: c.getConfigValue("omero.bioformats.vcs_revision")
Out[2]: 'b54fbdf9a057cb7a48de43a7ceaacda7e50789e4'
```

**Comment by chris-allan** [comment]
:+1:

Not sure if anyone cares about the exact Git SHA that was the source for the artifact but it can't hurt to have it.

**Review by sbesson — APPROVED** [review]
See https://github.com/ome/omero-common/pull/33#pullrequestreview-814675115, I assume another commit will be needed to bump the dependency once the upstream components are released.

**Pull request merged**
