### PR TITLE
ISession: add getSessionQuietly method

### PR DESCRIPTION
**Pull request by joshmoore**
Add a method which allows loading a session without
updating its last access time.

### CODE REVIEW

**Comment by joshmoore** [comment]
This is a first step toward https://github.com/ome/omero-blitz/issues/55 but may not suffice since currently there's no infrastructure for calling `ome.api.local` interfaces from `IceMethodInvoker` which means that the following is failing:

```
+        boolean quietly = false;
+        if (__current != null && __current.ctx != null) {
+            quietly = Boolean.valueOf(__current.ctx.getOrDefault("quietly", "false"));
+        }
+
+        try {
+            if (quietly) {
+                __current.operation = "getSessionQuietly";
+            }
+            callInvokerOnRawArgs(__cb, __current, sessionUuid);
+        } finally {
+            if (quietly) {
+                __current.operation = "getSession";
+            }
+        }
```

If I can't come up with an easy fix, the API change here will likely need to be pushed down to `omero-common`.

**Comment by joshmoore** [comment]
Looking good now. @pwalczysko: with this set of changes, I'd imagine that tomorrow's build would *not* show the hanging that you have been seeing. Independently, though, it'd be good to have web proactively closing the tables so we're not waiting on session closure.

**Comment by pwalczysko** [comment]
https://merge-ci.openmicroscopy.org/web/  I suppose ?

**Comment by joshmoore** [comment]
> https://merge-ci.openmicroscopy.org/web/ I suppose ?

@pwalczysko : indeed

**Comment by pwalczysko** [comment]
Please ping when this is ready to test. Thanks

**Comment by joshmoore** [comment]
@pwalczysko : https://github.com/ome/omero-blitz/pull/60 is green and will be included in the next run of merge-ci.

**Comment by pwalczysko** [comment]
The test today as user-2 who opened a table and then did not log out shows that the fix here works. But see https://github.com/ome/scripts/pull/148#issuecomment-505010905

**Comment by joshmoore** [comment]
The issue you are seeing there, @pwalczysko, is separate and related to https://github.com/ome/omero-blitz/pull/57

I'm going to merge the `getSessionQuietly` set of PRs together and then we can verify them independently on latest to evaluate the table closer work.

**Comment by joshmoore** [comment]
Note, @jburel, that this might warrant an omero-server release and a bump in omero-blitz since it adds a new method.

**Comment by pwalczysko** [comment]
>I'm going to merge the getSessionQuietly set of PRs together and then we can verify them independently on latest to evaluate the table closer work.

This is done now (tested latest-ci for a user who just opens a table and then closes the tab in browser). Test passed (the session of that user expired in 10 mins)

**Comment by pwalczysko** [comment]
cc @joshmoore (see https://github.com/ome/omero-server/pull/56#issuecomment-506690490) - sorry, forgot to mention you directly in the comment

**Comment by joshmoore** [comment]
Great. Thanks, @pwalczysko

**Pull request merged**
