### PR TITLE
Allow sending of e-mail with TLS.

### LINKED ISSUE #109: Sending mail to encrypted SMTP seems to be broken
see:
 - https://forum.image.sc/t/password-reset-email-config/35701/6
 - https://forum.image.sc/t/how-to-debug-the-omero-mail-system/42731/3
 - https://docs.openmicroscopy.org/omero/5.6/sysadmins/config.html#mail
 - https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html

Investigations into the above forum threads seems to point to some combination of current Java version, mail providers (minimally gmail), and the current server version (5.6.1) not being able to send mail over SSL/TCP. (Examples in Dundee work when sending to unencrypted servers)

### PR DESCRIPTION
**Pull request by mtbc**
Fixes #109. The following is akin to a working configuration:
```
omero.mail.config=true
omero.mail.from=whatever@gmail.com
omero.mail.host=smtp.googlemail.com
omero.mail.port=587
omero.mail.smtp.auth=true
omero.mail.username=whatever@gmail.com
omero.mail.password=mypassword
omero.mail.smtp.starttls.enable=true
```
Alternatively, changing the port number and the last line,
```
omero.mail.config=true
omero.mail.from=whatever@gmail.com
omero.mail.host=smtp.googlemail.com
omero.mail.port=465
omero.mail.smtp.auth=true
omero.mail.username=whatever@gmail.com
omero.mail.password=mypassword
omero.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
```
This needs your account to enable "Less secure app access". You can also try mail services other than Google's.

### CODE REVIEW

**Comment by manics** [comment]
> If you prefer to use port 465 then you probably need to use a SSLSocketFactory instead of the STARTTLS.

Do you mean it's supported by omero-server but you need to use the correct configuration? Or would smpts require code changes?

**Comment by mtbc** [comment]
I mean that it's supported, just *instead* of `omero.mail.smtp.starttls.enable=true` one sets `omero.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory` - I *think* that'll work on GMail's 465, certainly something like that does because I happened upon it in today's testing.

Some variant setting `smtps` as the protocol might also work but I didn't much explore that in my testing, it might generally be better if the server weren't setting `omero.mail.smtp.socketFactory.*` at all, as I suspect it of being nicely automated based on protocol and such, but I figure that's another story, for a rainy day.

**Comment by mtbc** [comment]
> certainly something like that does

It does, retested it and updated the description.

**Comment by mtbc** [comment]
I've tried with OpenJDK both 1.8.0_265 and 11.0.8. Where convenient, probably best to vary platform in testing.

**Comment by joshmoore** [comment]
First configuration (port 587):
```
Successfully sent 1 of 1 emails
```

Second configuration port 465):
```
Successfully sent 1 of 1 emails
```
:+1:

**Review by joshmoore — APPROVED** [review]
Happy to see this go in as is. There _might_ be room for adding on top of this configuration 2 or three `mailSender` beans (along with associated sub-beans) in order to allow someone to just use:

```
omero config set omero.mail.bean sslMailBean # or tlsMailBean
```

but that's certainly just a nice to have.

**Comment by joshmoore** [comment]
> This needs your account to enable "Less secure app access". You can also try mail services other than Google's.

Alternatively, 2-factor and an app password suffices. (Note: that's what I used in my original testing as well)

**Pull request merged**
