### PR TITLE
version tmp

### PR DESCRIPTION
**Pull request by jburel**
Bump the version to hopefully stabilise the tests
This should not be merged

### CODE REVIEW

**Comment by jburel** [comment]
This definitely has an impact on the tests see https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-test-integration/358/
cc @joshmoore

**Comment by mtbc** [comment]
Now running with latest commit at https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-test-integration/360/.

**Comment by mtbc** [comment]
Server failed to start:

> Could not resolve placeholder 'omero.version' in value "${omero.version}"

**Comment by jburel** [comment]
@mtbc thanks. Reverting so we do not break more. 
We will need to do further testing

**Comment by jburel** [comment]
Closing this PR. Otherwise it will conflict with #30

**Pull request closed without merging**
